### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by cecton** [destream-py/destream#14]
Hi everyone :wave: 

I am glad that this project helped some people managing archives. Unfortunately it is now time for me to move on. One of the main reason is that I didn't have a use for this library for a very long time now. Another reason is that I don't use much Python anymore either.

I believe a team of interested people can bring this project to the next level with more features, better code quality and better stability and tests.

That's why I think this project should go back to the community. I would like to create an organization with a few maintainers and owners for it. The more the merrier. If you are interested in adopting destream, please let me know.

Kind regards and thank you for your interest

cc @jruere @ziord @gauravssnl @luenix @ayoshi @Phyllostachys @shekkbuilder @Meroje

**Comment by jruere** [comment]
I'd be glad to maintain but I'd try to **not** add new features as much as possible.

**Comment by cecton** [comment]
@jruere thanks a lot!!

Okay let's do this. I will transfer the ownership of the repo and add you as owner on pypi. Can you give me your user id pypi?

**Comment by jruere** [comment]
`jruere`

**Comment by jruere** [comment]
Well, stay as backup. You can find the next maintainer when I die. :D

**Comment by cecton** [comment]
@jruere can you also give me your email address?

**Comment by cecton** [comment]
destream is already taken, I will go for destream-py (unless you have another idea?)

**Comment by jruere** [comment]
Sounds good!

**Comment by eumiro** [comment]
Hello to the team! I think we can close this issue and see how it goes on. Usually the active contributors make the best joining maintainers.

**Comment by cecton** [comment]
Closing for now but anyone should feel free to ask here if they want to join the party
